# Generated by Django 5.0.4 on 2024-05-24 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeRise', '0002_alter_recipe_user_id_reviews_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Recipes',
        ),
    ]
