# Generated by Django 5.0.4 on 2024-05-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeRise', '0003_rename_recipe_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='user_id',
            new_name='user',
        ),
    ]
